//THIS CLASS IS ONLY USED WHEN CREATING A NEW PRODUCT 
//(it contains no "id" field, since the id will be autogenerated when sent to the backend)

export class newProduct {
    quantity: number;
    price: number;
    description: string;
    image: string;
    name: string;
    more_details: string;


    constructor (quantity: number, price: number, description: string, image: string, name: string,  more_details: string) {
        this.name = name;
        this.quantity = quantity;
        this.description = description;
        this.price = price;
        this.image = image;
        this.more_details = more_details;
    }
}